const express = require('express')
const dbConnect = require('./config/dbConnect')
const app = express()
const dotenv = require('dotenv').config()
const PORT = process.env.PORT || 3000
const authRouter = require('./routers/authRouter')
const productRouter = require('./routers/productRouter')
const blogRouter = require('./routers/blogRouter')
const blogCateRouter = require('./routers/blogCateRouter')
const productCategoryRouter = require('./routers/productCategoryRouter')
const brandRouter = require('./routers/brandRouter')
const couponRouter = require('./routers/couponRouter')
const bodyParser = require('body-parser')
const { notFound, errorHandler } = require('./middlewares/errorHandler')
const cookieParser = require('cookie-parser')
const morgan = require('morgan')
dbConnect()

app.use(morgan('dev'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: false }))
app.use(cookieParser())

app.use('/api/user', authRouter)
app.use('/api/product', productRouter)
app.use('/api/blog', blogRouter)
app.use('/api/blogCate', blogCateRouter)
app.use('/api/brand', brandRouter)
app.use('/api/category', productCategoryRouter)
app.use('/api/coupon', couponRouter)
app.use(notFound)
app.use(errorHandler)
app.listen(PORT, () => {
  console.log(`Server is running at PORT: ${PORT}`)
})
